### ISSUE TITLE
That you can't play with keyboard alone is incredibly frustrating

### ISSUE THREAD

**Issue by CatzHoekk** [brendaninnis/satle#13]
When you type something and reduce the available options to just one, pressing enter should act as if you typed exactly the last option and lock that in.

If there are more options, you should be able to select an option using the up and down arrowkeys to select which one you mean.
That you HAVE TO use the mouse to select the city is incredibly annoying.

Would be great if that could be added.

**Comment by brendaninnis** [comment]
That does sound incredibly frustrating. Thanks for letting me know! 🙇

**Comment by brendaninnis** [comment]
I've rolled out a fix for this to satle.ca. You should see it next time you play, but you may need to clear your cache if that doesn't work. Please feel free to reopen the issue if it's not fixed.

You should now see:
1. The guess box is focused after the page loads so you can start typing right away, no need to click the text box.
2. You can use keyboard 'up' and 'down' buttons to select autocomplete suggestions.
3. Pressing 'enter' will fill the autocomplete suggestion, or submit the guess if there is only one.

**Comment by CatzHoekk** [comment]
Nice. That was quick. This is so much better. Thank you very much.

Here's how my first game went. 

![image](https://github.com/user-attachments/assets/52eacd63-0d9a-40b7-a1d0-4f10e53380cb)

(The skips were unintentional, but absolutely my mistake, just pressing enter twice because of response time or just because i didn't even know submitting an empty guess would do anything)

I will play a couple of days and see if i keep repeating the unintentional skipping. If i feel like skipping should be prevented for a short period of time after going to a new level or so, i will open a new issue.
