### ISSUE TITLE
Statistics not working

### ISSUE THREAD

**Issue by tomascarl** [brendaninnis/satle#5]
Since a couple of weeks, the statistics doesn't update

**Comment by brendaninnis** [comment]
Thanks for opening this issue.

Yes unfortunately I have not been able to add new puzzles as quickly as I thought I would. I did not realize that using previous puzzles would break the statistics and the window.

I will make an update first with new puzzles, and this issue will be fixed after.

**Comment by brendaninnis** [comment]
This was fixed in [PR 6](https://github.com/brendaninnis/satle/pull/6) 👍
